<a href="https://colab.research.google.com/github/razankablan/razankablan-data-analysis-exercises/blob/main/Presentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%matplotlib inline

In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving bitcoin.csv to bitcoin.csv

In [ ]:
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

User uploaded file "bitcoin.csv" with length 48089 bytes

In [ ]:
uploaded

{'bitcoin.csv': b'date,open,high,low,close,volume,market_cap\n2017-01-01,963.66,1003.08,958.7,998.33,147775008,16050407461\n2017-01-02,998.62,1031.39,996.7,1021.75,222184992,16429024775\n2017-01-03,1021.6,1044.08,1021.6,1043.84,185168000,16786368910\n2017-01-04,1044.4,1159.42,1044.4,1154.73,344945984,18571869009\n2017-01-05,1156.73,1191.1,910.42,1013.38,510199008,16300254795\n2017-01-06,1014.24,1046.81,883.94,902.2,351876000,14513695758\n2017-01-07,903.49,908.59,823.56,908.59,279550016,14618030536\n2017-01-08,908.17,942.72,887.25,911.2,158715008,14661966429\n2017-01-09,913.24,913.69,879.81,902.83,141876992,14528815565\n2017-01-10,902.44,914.87,901.06,907.68,115808000,14608685049\n2017-01-11,908.11,919.45,762.77,777.76,310928992,12519135996\n2017-01-12,775.18,826.25,755.76,804.83,222326000,12956730411\n2017-01-13,803.74,829.0,780.0,823.98,168968000,13266554392\n2017-01-14,825.14,835.09,812.46,818.41,93063296,13178601992\n2017-01-15,818.14,823.31,812.87,821.8,71013600,13234840657\n2017-01-16,821.78,834.53,820.27,831.53,82755200,13393372620\n2017-01-17,830.95,910.56,830.8,907.94,155095008,14625779851\n2017-01-18,909.37,917.5,858.3,886.62,225676992,14284036613\n2017-01-19,888.34,904.61,884.34,899.07,105625000,14486616700\n2017-01-20,898.17,899.4,887.01,895.03,86728400,14423545371\n2017-01-21,895.55,927.37,895.53,921.79,111158000,14856911163\n2017-01-22,922.21,937.53,897.56,924.67,116573000,14905439337\n2017-01-23,925.5,928.27,916.74,921.01,73588600,14848013909\n2017-01-24,910.68,924.15,892.29,892.69,111349000,14393026385\n2017-01-25,891.92,903.25,891.69,901.54,120831000,14537488261\n2017-01-26,902.4,919.33,902.22,917.59,131958000,14797955301\n2017-01-27,918.36,923.22,915.85,919.75,125594000,14834831700\n2017-01-28,919.81,923.91,919.81,921.59,68979600,14866260449\n2017-01-29,922.07,923.42,919.15,919.5,60851700,14834377926\n2017-01-30,920.15,923.05,919.47,920.38,78227296,14850351605\n2017-01-31,920.96,972.02,920.96,970.4,164582000,15659186515\n2017-02-01,970.94,989.11,970.74,989.02,150110000,15962015276\n2017-02-02,990.0,1013.52,983.22,1011.8,145820992,16331615570\n2017-02-03,1011.46,1033.87,1008.79,1029.91,201278000,16625849489\n2017-02-04,1031.33,1045.9,1015.16,1042.9,155064000,16837411920\n2017-02-05,1043.52,1043.63,1022.37,1027.34,114208000,16588240157\n2017-02-06,1028.4,1044.64,1028.16,1038.15,111762000,16764422010\n2017-02-07,1040.14,1061.93,1040.14,1061.35,146007008,17141080574\n2017-02-08,1062.32,1078.97,1037.49,1063.07,201855008,17170799127\n2017-02-09,1064.7,1088.99,953.34,994.38,407220000,16063448932\n2017-02-10,995.63,998.91,946.69,988.67,190452000,15973053725\n2017-02-11,988.9,1009.29,982.83,1004.45,102261000,16229677099\n2017-02-12,1003.52,1004.76,996.92,999.18,67530000,16146290349\n2017-02-13,998.89,1002.1,976.0,990.64,100607000,16010322103\n2017-02-14,991.73,1011.51,986.47,1004.55,137946000,16237219721\n2017-02-15,1006.21,1008.84,1001.58,1007.48,89759400,16286329282\n2017-02-16,1007.65,1033.37,1007.65,1027.44,122277000,16610905026\n2017-02-17,1026.12,1053.17,1025.64,1046.21,136474000,16916338976\n2017-02-18,1049.21,1061.1,1046.96,1054.42,99073504,17051064834\n2017-02-19,1054.76,1056.81,1043.46,1047.87,77423296,16946913346\n2017-02-20,1048.69,1080.49,1041.69,1079.98,109478000,17468244508\n2017-02-21,1079.28,1117.25,1076.93,1115.3,186868992,18041455273\n2017-02-22,1114.8,1125.39,1100.55,1117.44,136100000,18077985665\n2017-02-23,1117.27,1176.62,1116.96,1166.72,189454000,18877442096\n2017-02-24,1172.71,1200.39,1131.96,1173.68,330759008,18992415818\n2017-02-25,1170.41,1174.85,1124.59,1143.84,139960992,18511906560\n2017-02-26,1144.27,1167.47,1130.2,1165.2,116486000,18860247630\n2017-02-27,1163.78,1181.98,1163.38,1179.97,131570000,19101427518\n2017-02-28,1180.72,1193.25,1171.82,1179.97,184956000,19103684801\n2017-03-01,1180.04,1222.5,1179.69,1222.5,229056992,19794459608\n2017-03-02,1224.68,1262.13,1215.62,1251.01,368275008,20258543188\n2017-03-03,1250.71,1280.31,1250.71,1274.99,315739008,20649259919\n2017-03-04,1277.43,1279.4,1230.51,1255.15,183270000,20329978338\n2017-03-05,1254.29,1267.29,1238.06,1267.12,134127000,20526235270\n2017-03-06,1267.47,1276.0,1264.6,1272.83,153656992,20620991547\n2017-03-07,1273.21,1275.55,1204.8,1223.54,291256000,19824773912\n2017-03-08,1223.23,1232.16,1148.08,1150.0,332603008,18635275050\n2017-03-09,1150.35,1197.46,1141.23,1188.49,212283008,19261188310\n2017-03-10,1189.36,1270.47,1077.25,1116.72,563795968,18100188612\n2017-03-11,1116.32,1193.83,1116.32,1175.83,283320000,19060468862\n2017-03-12,1176.62,1226.98,1175.36,1221.38,227176000,19801195767\n2017-03-13,1221.78,1237.37,1217.03,1231.92,380276992,19974334865\n2017-03-14,1232.16,1244.81,1220.72,1240.0,245306000,20107761880\n2017-03-15,1240.16,1251.61,1239.75,1249.61,297804992,20265831337\n2017-03-16,1251.33,1257.98,1152.44,1187.81,638568000,19265847025\n2017-03-17,1180.16,1180.16,1099.57,1100.23,706598976,17847435957\n2017-03-18,1099.69,1114.07,957.66,973.82,621302016,15798760668\n2017-03-19,976.73,1069.91,976.73,1036.74,406648000,16821676707\n2017-03-20,1037.24,1063.03,1036.68,1054.23,286529984,17107266418\n2017-03-21,1055.36,1122.43,1055.36,1120.54,337391008,18185299687\n2017-03-22,1120.65,1120.65,1014.21,1049.14,380840992,17028630158\n2017-03-23,1050.05,1058.01,1028.93,1038.59,248540000,16859314109\n2017-03-24,1038.45,1040.47,934.36,937.52,491038016,15220718764\n2017-03-25,936.54,975.76,903.71,972.78,435803008,15794781102\n2017-03-26,974.02,1007.96,954.19,966.72,303668000,15698465531\n2017-03-27,972.05,1046.4,971.98,1045.77,372535008,16983801541\n2017-03-28,1044.58,1064.65,1027.73,1047.15,326332000,17008241726\n2017-03-29,1046.08,1055.13,1015.88,1039.97,298457984,16893415156\n2017-03-30,1042.21,1049.29,1020.04,1026.43,352968992,16675587066\n2017-03-31,1026.64,1074.92,1026.64,1071.79,447287008,17414322808\n2017-04-01,1071.71,1091.72,1061.09,1080.5,289633984,17557597716\n2017-04-02,1080.61,1107.59,1075.45,1102.17,514187008,17911915755\n2017-04-03,1102.95,1151.74,1102.95,1143.81,580444032,18591158323\n2017-04-04,1145.52,1156.44,1120.52,1133.25,436310016,18421262063\n2017-04-05,1134.14,1135.09,1113.63,1124.78,414784000,18285857775\n2017-04-06,1125.81,1188.37,1125.81,1182.68,511222016,19229356147\n2017-04-07,1178.94,1186.58,1163.39,1176.9,317022016,19137747435\n2017-04-08,1172.65,1184.98,1162.58,1175.95,209312000,19124327856\n2017-04-09,1176.57,1197.21,1171.86,1187.87,242343008,19320511927\n2017-04-10,1187.3,1190.34,1179.04,1187.13,215883008,19310642460\n2017-04-11,1187.46,1208.07,1187.46,1205.01,216182000,19604036563\n2017-04-12,1204.81,1207.14,1196.76,1200.37,288702016,19530680104\n2017-04-13,1201.02,1205.89,1156.44,1169.28,351968992,19026699552\n2017-04-14,1170.33,1190.8,1159.79,1167.54,254827008,19000400018\n2017-04-15,1167.3,1188.0,1164.96,1172.52,203559008,19083656460\n2017-04-16,1172.61,1187.22,1172.61,1182.94,183231008,19255408766\n2017-04-17,1183.25,1194.9,1172.65,1193.91,253206000,19436033390\n2017-04-18,1193.77,1217.57,1193.77,1211.67,270524000,19727334977\n2017-04-19,1212.13,1215.51,1205.08,1210.29,288060992,19707045565\n2017-04-20,1211.08,1240.79,1208.41,1229.08,315108000,20015137622\n2017-04-21,1229.42,1235.94,1215.56,1222.05,272167008,19903192286\n2017-04-22,1222.71,1235.56,1208.47,1231.71,249320000,20062753908\n2017-04-23,1231.92,1232.2,1203.94,1207.21,258951008,19665994145\n2017-04-24,1209.63,1250.94,1209.63,1250.15,235806000,20367443800\n2017-04-25,1250.45,1267.58,1249.97,1265.49,242556000,20619704237\n2017-04-26,1265.99,1294.83,1265.93,1281.08,329631008,20876159410\n2017-04-27,1281.88,1319.7,1281.3,1317.73,449196992,21475836448\n2017-04-28,1317.74,1331.28,1292.37,1316.48,527488992,21457669552\n2017-04-29,1317.84,1327.2,1315.21,1321.79,422705984,21547126640\n2017-04-30,1321.87,1347.91,1314.92,1347.89,413115008,21975104909\n2017-05-01,1348.3,1434.32,1348.3,1421.6,713624000,23179524919\n2017-05-02,1421.03,1473.9,1415.69,1452.82,477337984,23691443738\n2017-05-03,1453.78,1492.77,1447.49,1490.09,583795968,24301634925\n2017-05-04,1490.72,1608.91,1490.72,1537.67,933548992,25080858487\n2017-05-05,1540.87,1618.03,1530.31,1555.45,946035968,25373374563\n2017-05-06,1556.81,1578.8,1542.5,1578.8,582529984,25757608890\n2017-05-07,1579.47,1596.72,1559.76,1596.71,1080029952,26053077975\n2017-05-08,1596.92,1723.35,1596.92,1723.35,1340320000,28123369330\n2017-05-09,1723.89,1833.49,1716.3,1755.36,1167920000,28649119972\n2017-05-10,1756.52,1788.44,1719.1,1787.13,915723008,29170965564\n2017-05-11,1780.37,1873.93,1755.35,1848.57,799489984,30176934751\n2017-05-12,1845.76,1856.15,1694.01,1724.24,740984000,28150631936\n2017-05-13,1723.12,1812.99,1651.08,1804.91,579635008,29471223857\n2017-05-14,1800.86,1831.42,1776.62,1808.91,437196000,29540290794\n2017-05-15,1808.44,1812.8,1708.54,1738.43,731529024,28392885375\n2017-05-16,1741.7,1785.94,1686.54,1734.45,959044992,28330874003\n2017-05-17,1726.73,1864.05,1661.91,1839.09,1064729984,30043626195\n2017-05-18,1818.7,1904.48,1807.12,1888.65,894321024,30856574835\n2017-05-19,1897.37,2004.52,1890.25,1987.71,1157289984,32479082015\n2017-05-20,1984.24,2084.73,1974.92,2084.73,961336000,34068630559\n2017-05-21,2067.03,2119.08,2037.5,2041.2,1147859968,33361091114\n2017-05-22,2043.19,2303.9,2017.87,2173.4,1942220032,35525744380\n2017-05-23,2191.56,2320.82,2178.5,2320.42,1378749952,37933704066\n2017-05-24,2321.37,2523.72,2321.37,2443.64,1725379968,39952841999\n2017-05-25,2446.24,2763.71,2285.3,2304.98,2406700032,37690456715\n2017-05-26,2320.89,2573.79,2071.99,2202.42,1763480064,36017660894\n2017-05-27,2196.27,2260.2,1855.83,2038.87,1700480000,33347170525\n2017-05-28,2054.08,2267.34,2054.08,2155.8,1147139968,35264171110\n2017-05-29,2159.43,2307.05,2107.17,2255.61,994625024,36901102917\n2017-05-30,2255.36,2301.96,2124.57,2175.47,1443970048,35594903085\n2017-05-31,2187.19,2311.08,2145.57,2286.41,1544829952,37414813240\n2017-06-01,2288.33,2448.39,2288.33,2407.88,1653180032,39407633763\n2017-06-02,2404.03,2488.55,2373.32,2488.55,1317030016,40732491835\n2017-06-03,2493.72,2581.91,2423.57,2515.35,1514950016,41177190057\n2017-06-04,2547.79,2585.89,2452.54,2511.81,1355120000,41124262595\n2017-06-05,2512.4,2686.81,2510.22,2686.81,1369309952,43994968834\n2017-06-06,2690.84,2999.91,2690.84,2863.2,2089609984,46888622160\n2017-06-07,2869.38,2869.38,2700.56,2732.16,1517709952,44748237218\n2017-06-08,2720.49,2815.3,2670.95,2805.62,1281170048,45957247989\n2017-06-09,2807.44,2901.71,2795.62,2823.81,1348950016,46260465854\n2017-06-10,2828.14,2950.99,2746.55,2947.71,2018889984,48295501718\n2017-06-11,2942.41,2996.6,2840.53,2958.11,1752400000,48471330146\n2017-06-12,2953.22,2997.26,2518.56,2659.63,2569530112,43585351533\n2017-06-13,2680.91,2789.04,2650.38,2717.02,1781200000,44530631894\n2017-06-14,2716.88,2786.83,2412.94,2506.37,1696560000,41082567339\n2017-06-15,2499.58,2534.71,2212.96,2464.58,2026259968,40402259202\n2017-06-16,2469.57,2539.92,2385.15,2518.56,1195190016,41291821423\n2017-06-17,2514.01,2685.19,2484.96,2655.88,1534509952,43548031452\n2017-06-18,2655.35,2662.1,2516.33,2548.29,1178659968,41788418974\n2017-06-19,2549.03,2662.85,2549.03,2589.6,1446840064,42470734800\n2017-06-20,2591.26,2763.45,2589.82,2721.79,1854189952,44643512689\n2017-06-21,2709.43,2772.01,2660.4,2689.1,1626579968,44111929173\n2017-06-22,2691.03,2723.74,2642.36,2705.41,1097939968,44384244937\n2017-06-23,2707.34,2765.17,2706.37,2744.91,961318976,45037797053\n2017-06-24,2738.52,2757.94,2583.19,2608.72,982750016,42807952581\n2017-06-25,2607.25,2682.26,2552.12,2589.41,1161100032,42495001716\n2017-06-26,2590.57,2615.25,2376.29,2478.45,1663280000,40677994354\n2017-06-27,2478.45,2552.45,2332.99,2552.45,1489789952,41897190525\n2017-06-28,2553.03,2603.98,2484.42,2574.79,1183869952,42268942193\n2017-06-29,2567.56,2588.83,2510.48,2539.32,949979008,41690395783\n2017-06-30,2539.24,2559.25,2478.43,2480.84,860273024,40735082695\n2017-07-01,2492.6,2515.27,2419.23,2434.55,779913984,39980058373\n2017-07-02,2436.4,2514.28,2394.84,2506.47,803747008,41167015221\n2017-07-03,2498.56,2595.0,2480.47,2564.06,964112000,42118211083\n2017-07-04,2561.0,2631.59,2559.35,2601.64,985516032,42740618673\n2017-07-05,2602.87,2622.65,2538.55,2601.99,941566016,42751085999\n2017-07-06,2608.1,2616.72,2581.69,2608.56,761956992,42863758795\n2017-07-07,2608.59,2916.14,2498.87,2518.66,917411968,41391217675\n2017-07-08,2520.27,2571.34,2492.31,2571.34,733329984,42262222823\n2017-07-09,2572.61,2635.49,2517.59,2518.44,527856000,41397076604\n2017-07-10,2525.25,2537.16,2321.13,2372.56,1111200000,39005033499\n2017-07-11,2385.89,2413.47,2296.81,2337.79,1329760000,38438497236\n2017-07-12,2332.77,2423.71,2275.14,2398.84,1117410048,39447604438\n2017-07-13,2402.7,2425.22,2340.83,2357.9,835769984,38778935907\n2017-07-14,2360.59,2363.25,2183.22,2233.34,882502976,36734255488\n2017-07-15,2230.12,2231.14,1990.41,1998.86,993608000,32880721300\n2017-07-16,1991.98,2058.77,1843.03,1929.82,1182870016,31748939343\n2017-07-17,1932.62,2230.49,1932.62,2228.41,1201760000,36665393517\n2017-07-18,2233.52,2387.61,2164.77,2318.88,1512450048,38158677672\n2017-07-19,2323.08,2397.17,2260.23,2273.43,1245100032,37415031061\n2017-07-20,2269.89,2900.7,2269.89,2817.6,2249260032,46376428080\n2017-07-21,2838.41,2838.41,2621.85,2667.76,1489449984,43915296559\n2017-07-22,2668.63,2862.42,2657.71,2810.12,1177129984,46264340367\n2017-07-23,2808.1,2832.18,2653.94,2730.4,1072840000,44957775265\n2017-07-24,2732.7,2777.26,2699.19,2754.86,866473984,45366654309\n2017-07-25,2757.5,2768.08,2480.96,2576.48,1460089984,42433788244\n2017-07-26,2577.77,2610.76,2450.8,2529.45,937404032,41663929265\n2017-07-27,2538.71,2693.32,2529.34,2671.78,789104000,44013533097\n2017-07-28,2679.73,2897.45,2679.73,2809.01,1380099968,46279316161\n2017-07-29,2807.02,2808.76,2692.8,2726.45,803745984,44924534585\n2017-07-30,2724.39,2758.53,2644.85,2757.18,705942976,45435913868\n2017-07-31,2763.24,2889.62,2720.61,2875.34,860574976,47388334773\n2017-08-01,2871.3,2921.35,2685.61,2718.26,1324669952,44804603885\n2017-08-02,2727.13,2762.53,2668.59,2710.67,1094950016,44684649516\n2017-08-03,2709.56,2813.31,2685.14,2804.73,804796992,46239970790\n2017-08-04,2806.93,2899.33,2743.72,2895.89,1002120000,47749461443\n2017-08-05,2897.63,3290.01,2874.83,3252.91,1945699968,53643452554\n2017-08-06,3257.61,3293.29,3155.6,3213.94,1105030016,53006426108\n2017-08-07,3212.78,3397.68,3180.89,3378.94,1482279936,55734179251\n2017-08-08,3370.22,3484.85,3345.83,3419.94,1752760064,56417337745\n2017-08-09,3420.4,3422.76,3247.67,3342.47,1468960000,55145196472\n2017-08-10,3341.84,3453.45,3319.47,3381.28,1515110016,55791120000\n2017-08-11,3373.82,3679.72,3372.12,3650.62,2021190016,60241844923\n2017-08-12,3650.63,3949.92,3613.7,3884.71,2219589888,64111163866\n2017-08-13,3880.04,4208.39,3857.8,4073.26,3159089920,67230528989\n2017-08-14,4066.1,4325.13,3989.16,4325.13,2463089920,71394704654\n2017-08-15,4326.99,4455.97,3906.18,4181.93,3258050048,69038855081\n2017-08-16,4200.34,4381.23,3994.42,4376.63,2272039936,72260183303\n2017-08-17,4384.44,4484.7,4243.71,4331.69,2553359872,71527949443\n2017-08-18,4324.34,4370.13,4015.4,4160.62,2941710080,68710871037\n2017-08-19,4137.75,4243.26,3970.55,4193.7,2975820032,69265141208\n2017-08-20,4189.31,4196.29,4069.88,4087.66,2109769984,67520478838\n2017-08-21,4090.48,4109.14,3988.6,4001.74,2800890112,66106992038\n2017-08-22,3998.35,4128.76,3674.58,4100.52,3764239872,67743202431\n2017-08-23,4089.01,4255.78,4078.41,4151.52,2369819904,68593954170\n2017-08-24,4137.6,4376.39,4130.26,4334.68,2037750016,71625870868\n2017-08-25,4332.82,4455.7,4307.35,4371.6,1727970048,72241507489\n2017-08-26,4372.06,4379.28,4269.52,4352.4,1511609984,71929882019\n2017-08-27,4345.1,4416.59,4317.29,4382.88,1537459968,72441993792\n2017-08-28,4384.45,4403.93,4224.64,4382.66,1959330048,72445588933\n2017-08-29,4389.21,4625.68,4352.13,4579.02,2486080000,75699786263\n2017-08-30,4570.36,4626.52,4471.41,4565.3,1937849984,75482724984\n2017-08-31,4555.59,4736.05,4549.4,4703.39,1944930048,77775374625\n2017-09-01,4701.76,4892.01,4678.53,4892.01,2599079936,80905039782\n2017-09-02,4901.42,4975.04,4469.24,4578.77,2722139904,75734114962\n2017-09-03,4585.27,4714.08,4417.59,4582.96,1933190016,75812181334\n2017-09-04,4591.63,4591.63,4108.4,4236.31,2987330048,70087101256\n2017-09-05,4228.29,4427.84,3998.11,4376.53,2697969920,72417728536\n2017-09-06,4376.59,4617.25,4376.59,4597.12,2172100096,76077049312\n2017-09-07,4589.14,4655.04,4491.33,4599.88,1844620032,76132843874\n2017-09-08,4605.16,4661.0,4075.18,4228.75,2700890112,69999555938\n2017-09-09,4229.81,4308.82,4114.11,4226.06,1386230016,69963847482\n2017-09-10,4229.34,4245.44,3951.04,4122.94,1679090048,68263826801\n2017-09-11,4122.47,4261.67,4099.4,4161.27,1557330048,68907352119\n2017-09-12,4168.88,4344.65,4085.22,4130.81,1864530048,68412822896\n2017-09-13,4131.98,4131.98,3789.92,3882.59,2219409920,64311123695\n2017-09-14,3875.37,3920.6,3153.86,3154.95,2716310016,52265453816\n2017-09-15,3166.3,3733.45,2946.62,3637.52,4148069888,60267886368\n2017-09-16,3637.75,3808.84,3487.79,3625.04,1818400000,60068678195\n2017-09-17,3606.28,3664.81,3445.64,3582.88,1239149952,59377995376\n2017-09-18,3591.09,4079.23,3591.09,4065.2,1943209984,67377945990\n2017-09-19,4073.79,4094.07,3868.87,3924.97,1563980032,65061185838\n2017-09-20,3916.36,4031.39,3857.73,3905.95,1213830016,64751811835\n2017-09-21,3901.47,3916.42,3613.63,3631.04,1411480064,60202370872\n2017-09-22,3628.02,3758.27,3553.53,3630.7,1194829952,60203040223\n2017-09-23,3629.92,3819.21,3594.58,3792.4,928113984,62892069389\n2017-09-24,3796.15,3796.15,3666.9,3682.84,768014976,61081971156\n2017-09-25,3681.58,3950.25,3681.58,3926.07,1374210048,65122213849\n2017-09-26,3928.41,3969.89,3869.9,3892.35,1043740032,64569365079\n2017-09-27,3892.94,4210.05,3884.82,4200.67,1686880000,69691950752\n2017-09-28,4197.13,4279.31,4109.7,4174.73,1712320000,69270823146\n2017-09-29,4171.62,4214.63,4039.29,4163.07,1367049984,69086146650\n2017-09-30,4166.11,4358.43,4160.86,4338.71,1207449984,72008428789\n2017-10-01,4341.05,4403.74,4269.81,4403.74,1208210048,73094870674\n2017-10-02,4395.81,4470.23,4377.46,4409.32,1431730048,73195646776\n2017-10-03,4408.46,4432.47,4258.89,4317.48,1288019968,71681069637\n2017-10-04,4319.37,4352.31,4210.42,4229.36,1116770048,70225033578\n2017-10-05,4229.88,4362.64,4164.05,4328.41,1161769984,71876277937\n2017-10-06,4324.46,4413.27,4320.53,4370.81,1069939968,72589262957\n2017-10-07,4369.35,4443.88,4321.05,4426.89,906928000,73529314833\n2017-10-08,4429.67,4624.14,4405.64,4610.48,1313869952,76589293760\n2017-10-09,4614.52,4878.71,4564.25,4772.02,1968739968,79282158943\n2017-10-10,4776.21,4922.17,4765.1,4781.99,1597139968,79457603224\n2017-10-11,4789.25,4873.73,4751.63,4826.48,1222279936,80205238020\n2017-10-12,4829.58,5446.91,4822.0,5446.91,2791610112,90525666972\n2017-10-13,5464.16,5840.3,5436.85,5647.21,3615480064,93864253934\n2017-10-14,5643.53,5837.7,5591.64,5831.79,1669030016,96942498331\n2017-10-15,5835.96,5852.48,5478.61,5678.19,1976039936,94403031755\n2017-10-16,5687.57,5776.23,5544.21,5725.59,2008070016,95203392843\n2017-10-17,5741.58,5800.35,5472.72,5605.51,1821570048,93218297189\n2017-10-18,5603.82,5603.82,5151.44,5590.69,2399269888,92982539106\n2017-10-19,5583.74,5744.35,5531.06,5708.52,1780540032,94954808115\n2017-10-20,5708.11,6060.11,5627.23,6011.45,2354429952,100007083345\n2017-10-21,5996.79,6194.88,5965.07,6031.6,2207099904,100353682389\n2017-10-22,6036.66,6076.26,5792.34,6008.42,2034630016,99981911326\n2017-10-23,6006.0,6075.59,5732.47,5930.32,2401840128,98695054084\n2017-10-24,5935.52,5935.52,5504.18,5526.64,2735699968,91988225800\n2017-10-25,5524.6,5754.33,5397.88,5750.8,1966989952,95732630220\n2017-10-26,5747.95,5976.8,5721.22,5904.83,1905040000,98310176011\n2017-10-27,5899.74,5988.39,5728.82,5780.9,1710130048,96254297360\n2017-10-28,5787.82,5876.72,5689.19,5753.09,1403920000,95797359518\n2017-10-29,5754.44,6255.71,5724.58,6153.85,2859040000,102482445590\n2017-10-30,6114.85,6214.99,6040.85,6130.53,1772150016,102105356519\n2017-10-31,6132.02,6470.43,6103.33,6468.4,2311379968,107743731291\n2017-11-01,6440.97,

In [ ]:
import pandas as pd
bitcoin = pd.read_csv("bitcoin.csv")

In [ ]:
df = pd.read_csv('/content/bitcoin.csv')

In [ ]:
import pandas as pd
import io

bitcoin_df = pd.read_csv(io.StringIO(uploaded['bitcoin.csv'].decode('utf-8')))

In [ ]:
bitcoin_df = pd.read_csv(io.StringIO(uploaded['bitcoin.csv'].decode('utf-8')))

In [ ]:
bitcoin_df.head()

         date     open     high      low    close     volume   market_cap
0  2017-01-01   963.66  1003.08   958.70   998.33  147775008  16050407461
1  2017-01-02   998.62  1031.39   996.70  1021.75  222184992  16429024775
2  2017-01-03  1021.60  1044.08  1021.60  1043.84  185168000  16786368910
3  2017-01-04  1044.40  1159.42  1044.40  1154.73  344945984  18571869009
4  2017-01-05  1156.73  1191.10   910.42  1013.38  510199008  16300254795

In [ ]:
bitcoin_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        730 non-null    object
 1   open        730 non-null    float64
 2   high        730 non-null    float64
 3   low         730 non-null    float64
 4   close       730 non-null    float64
 5   volume      730 non-null    int64
 6   market_cap  730 non-null    int64
dtypes: float64(4), int64(2), object(1)
memory usage: 40.1+ KB

In [ ]:
bitcoin_df.columns

Index(['date', 'open', 'high', 'low', 'close', 'volume', 'market_cap'], dtype='object')

In [ ]:
# Check for missing values
bitcoin_df.isnull().sum()

# View rows that contain any NaN values
bitcoin_df[bitcoin_df.isnull().any(axis=1)]

Empty DataFrame
Columns: [date, open, high, low, close, volume, market_cap]
Index: []

In [ ]:
bitcoin_df['close'].fillna(bitcoin_df['close'].mean(), inplace=True)

bitcoin_df.fillna(method='ffill', inplace=True)

/tmp/ipython-input-2106442823.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bitcoin_df['close'].fillna(bitcoin_df['close'].mean(), inplace=True)
/tmp/ipython-input-2106442823.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  bitcoin_df.fillna(method='ffill', inplace=True)

In [ ]:
bitcoin_df.dropna(inplace=True)

In [ ]:
# Convert 'date' column to datetime
bitcoin_df['date'] = pd.to_datetime(bitcoin_df['date'])

# Convert numeric columns that might be strings
bitcoin_df['volume'] = pd.to_numeric(bitcoin_df['volume'], errors='coerce')

In [ ]:
# Check and remove duplicates
bitcoin_df.duplicated().sum()
bitcoin_df.drop_duplicates(inplace=True)

In [ ]:
import numpy as np

# Identify outliers using the Interquartile Range (IQR)
Q1 = bitcoin_df['close'].quantile(0.25)
Q3 = bitcoin_df['close'].quantile(0.75)
IQR = Q3 - Q1

# Filter out outliers
filtered_df = bitcoin_df[~((bitcoin_df['close'] < (Q1 - 1.5 * IQR)) | (bitcoin_df['close'] > (Q3 + 1.5 * IQR)))]

In [28]:
# Select specific columns
price_data = bitcoin_df[['date', 'close']]

# Filter rows – for example, Bitcoin prices above $10,000
high_price_df = bitcoin_df[bitcoin_df['close'] > 10000]

# Apply transformations – calculate daily return
bitcoin_df['daily_return'] = bitcoin_df['close'].pct_change() * 100

In [ ]:
import numpy as np

# Calculate log returns using NumPy
bitcoin_df['log_return'] = np.log(bitcoin_df['close'] / bitcoin_df['close'].shift(1))

# Create a new column classifying daily movement
bitcoin_df['trend'] = np.where(bitcoin_df['daily_return'] > 0, 'Gain', 'Loss')

In [ ]:
# Example 1: Extract month and year for trend analysis
bitcoin_df['month'] = bitcoin_df['date'].dt.month
bitcoin_df['year'] = bitcoin_df['date'].dt.year

# Example 2: Rolling averages (e.g., 7-day moving average)
bitcoin_df['7d_avg'] = bitcoin_df['close'].rolling(window=7).mean()

In [ ]:
#the 'trend' column (Gain/Loss)
trend_encoded = pd.get_dummies(bitcoin_df['trend'], prefix='trend')

# Merge with original DataFrame
bitcoin_df = pd.concat([bitcoin_df, trend_encoded], axis=1)

In [ ]:
bitcoin_df.head()

,date,open,high,low,close,volume,market_cap,daily_return,log_return,trend,trend_Gain,trend_Loss
0,2017-01-01,963.66,1003.08,958.70,998.33,147775008,16050407461,NaN,NaN,Loss,False,True
1,2017-01-02,998.62,1031.39,996.70,1021.75,222184992,16429024775,2.345918,0.023188,Gain,True,False
2,2017-01-03,1021.60,1044.08,1021.60,1043.84,185168000,16786368910,2.161977,0.021389,Gain,True,False
3,2017-01-04,1044.40,1159.42,1044.40,1154.73,344945984,18571869009,10.623276,0.100960,Gain,True,False
4,2017-01-05,1156.73,1191.10,910.42,1013.38,510199008,16300254795,-12.240957,-0.130575,Loss,False,True

from matplotlib import pyplot as plt
_df_0['open'].plot(kind='hist', bins=20, title='open')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['high'].plot(kind='hist', bins=20, title='high')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['low'].plot(kind='hist', bins=20, title='low')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['close'].plot(kind='hist', bins=20, title='close')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('trend').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_5.groupby('trend_Gain').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_6.groupby('trend_Loss').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='open', y='high', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8.plot(kind='scatter', x='high', y='low', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_9.plot(kind='scatter', x='low', y='close', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_10.plot(kind='scatter', x='close', y='volume', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['low']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('trend')):
  _plot_series(series, series_name, i)
  fig.legend(title='trend', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('low')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['low']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_12.sort_values('date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('trend_Gain')):
  _plot_series(series, series_name, i)
  fig.legend(title='trend_Gain', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('low')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['low']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_13.sort_values('date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('trend_Loss')):
  _plot_series(series, series_name, i)
  fig.legend(title='trend_Loss', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('low')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['close']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_14.sort_values('date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('trend')):
  _plot_series(series, series_name, i)
  fig.legend(title='trend', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('close')

from matplotlib import pyplot as plt
_df_15['open'].plot(kind='line', figsize=(8, 4), title='open')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_16['high'].plot(kind='line', figsize=(8, 4), title='high')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_17['low'].plot(kind='line', figsize=(8, 4), title='low')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_18['close'].plot(kind='line', figsize=(8, 4), title='close')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['trend_Gain'].value_counts()
    for x_label, grp in _df_19.groupby('trend')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('trend')
_ = plt.ylabel('trend_Gain')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['trend_Loss'].value_counts()
    for x_label, grp in _df_20.groupby('trend_Gain')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('trend_Gain')
_ = plt.ylabel('trend_Loss')

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_21['trend'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_21, x='open', y='trend', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_22['trend_Gain'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_22, x='open', y='trend_Gain', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_23['trend_Loss'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_23, x='open', y='trend_Loss', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_24['trend'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_24, x='high', y='trend', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN

# Create a presentation object
prs = Presentation()

# Function to add a slide with title and content
def add_slide(title, content):
    slide_layout = prs.slide_layouts[1]  # Title and Content layout
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = title
    textbox = slide.placeholders[1]
    textbox.text = content

# Slide contents
slides = [
    ("Bitcoin Data Wrangling & Analysis", "Using Python, pandas, and NumPy\nYour Name & Date"),
    ("Introduction", "Objective: Analyze historical Bitcoin data\nTools: Python, pandas, NumPy, Matplotlib/Seaborn\nFocus: Data cleaning, transformation, feature engineering, and reflections"),
    ("Dataset Overview", "Columns/features: date, open, high, low, close, volume, market_cap\nData types: date->datetime, close/open->float, volume/market_cap->int\nSample data snapshot:\nbitcoin_df.head()"),
    ("Handling Missing Data", "Identify missing values: bitcoin_df.isnull().sum()\nFill missing numeric values: bitcoin_df['close'].fillna(bitcoin_df['close'].mean(), inplace=True)\nForward-fill missing values: bitcoin_df.fillna(method='ffill', inplace=True)"),
    ("Data Type Conversion", "Convert date to datetime: bitcoin_df['date'] = pd.to_datetime(bitcoin_df['date'])\nConvert numeric columns: bitcoin_df['volume'] = pd.to_numeric(bitcoin_df['volume'], errors='coerce')"),
    ("Handling Duplicates and Outliers", "Check duplicates: bitcoin_df.duplicated().sum()\nRemove duplicates: bitcoin_df.drop_duplicates(inplace=True)\nDetect outliers using IQR method"),
    ("Feature Engineering", "Daily returns: bitcoin_df['daily_return'] = bitcoin_df['close'].pct_change() * 100\nLog returns: bitcoin_df['log_return'] = np.log(bitcoin_df['close'] / bitcoin_df['close'].shift(1))\nTrend classification: bitcoin_df['trend'] = np.where(bitcoin_df['daily_return'] > 0, 'Gain', 'Loss')\nExtract month/year: bitcoin_df['month'] = bitcoin_df['date'].dt.month") ,
    ("Transformation & Computation", "7-day rolling average: bitcoin_df['7d_avg'] = bitcoin_df['close'].rolling(window=7).mean()\nOne-hot encode trend: trend_encoded = pd.get_dummies(bitcoin_df['trend'], prefix='trend')\nbitcoin_df = pd.concat([bitcoin_df, trend_encoded], axis=1)"),
    ("Visualization Examples", "Plot close price and 7-day moving average:\nimport matplotlib.pyplot as plt\nplt.figure(figsize=(10,5))\nplt.plot(bitcoin_df['date'], bitcoin_df['close'], label='Close Price')\nplt.plot(bitcoin_df['date'], bitcoin_df['7d_avg'], label='7-Day Avg')\nplt.legend()\nplt.title('Bitcoin Close Price and 7-Day Moving Average')\nplt.xlabel('Date')\nplt.ylabel('Price (USD')\nplt.show()"),
    ("Key Lessons Learned", "Clean, structured data is crucial for reliable analysis\nFeature engineering unlocks insights (returns, trends, moving averages)\nVectorized operations (NumPy) simplify computations\nIterative process — clean, analyze, refine"),
    ("Challenges and Solutions", "Missing/inconsistent values → imputation/forward-fill\nOutliers due to market spikes → context-aware handling\nData type issues → conversions with pd.to_numeric and pd.to_datetime\nFeature engineering decisions → balance insight vs. simplicity"),
    ("Summary & Takeaways", "Python + pandas + NumPy = powerful toolkit for data wrangling\nClean and structured data is critical for analysis\nFeature engineering and transformations reveal hidden patterns\nSkills are transferable to financial and business datasets"),
    ("Documentation & Resources", "Python: https://docs.python.org/3/\nNumPy: https://numpy.org/doc/stable/\npandas: https://pandas.pydata.org/docs/\nBitcoin dataset: https://www.kaggle.com/datasets/mczielinski/bitcoin-historical-data"),
    ("Thank You / Q&A", "Contact info\nAny additional notes")
]

# Add slides
for title, content in slides:
    add_slide(title, content)

# Save presentation
file_path = '/mnt/data/Bitcoin_Data_Wrangling_Slides.pptx'
prs.save(file_path)
file_path

ModuleNotFoundError: No module named 'pptx'